# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgFBDfihbEdef0XdHBr9SMzhxslmsEVv
"""

import copy
import numpy as np
# 盤面を表示
def print_board(board):
    # 盤面の行と列のインデックスを表示するとデバッグに便利です
    print(board)

def step(a_t, board):
  board = board.flatten()
  #今の座標
  koma_num = int((a_t / 25)) + 1
  board = board.tolist()
  before = board.index(koma_num)

  #後の座標
  after = (a_t % 25)

  #金将の動きのエラーチェック
  info = 1
  if(after-before == 5):
    info = 0
  if(after-before == -5):
    info = 0
  if(after-before == 1 or after-before == -4):
    if((before%5) != 4):
      info = 0
  if(after-before == -1 or after-before == -6):
    if((before%5) != 0):
      info = 0

  #もともとの場所が自分の駒か
  if(board[before] <= 0):
    info = 1
  #移動先が自分の駒じゃないか
  if(board[after] > 0):
    info = 1

  if(board[after] == -3):
    if(board[before] != 3):
      info = 1

  #報酬設定
  r = 0
  done = 0
  if(info == 0):
    if(board[after] == 0):
      r = 0
    if(board[after] == -5 or board[after] == -1):
      r = 200
    if(board[after] == -4 or board[after] == -2):
      r = 100
    if(board[after] == -3):
      r = 300
      done = 1

    board[after] = board[before]
    board[before] = 0

  #勝利したかどうか

  borad2 = np.array(board)
  board = borad2.reshape(5, 5)

  return board, info, r, done

def reset():
  return np.array([
    [-5, -4, -3, -2, -1],  # 0-4 (プレイヤー2の駒)
    [0, 0, 0, 0, 0],       # 5-9
    [0, 0, 0, 0, 0],       # 10-14
    [0, 0, 0, 0, 0],       # 15-19
    [1, 2, 3, 4, 5]        # 20-24 (プレイヤー1の駒)
])

#開始
board = reset()

print("--- 初期盤面 ---")
print_board(board)

#a = nyuryoku()
a = 25*2+17

#自分の持ち点
count = 0

board, info, r, done = step(a, board, count)

print_board(board)

if(info == 0):
  print("エラーなし")
else:
  print("エラーあり")

print("報酬：" , r)
if(done == 1):
  print("勝利！")

